server:
  port: 9000
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods: "*"
      add-to-simple-url-handler-mapping: true
eureka:
  client:
    serviceUrl.defaultZone: http://eureka-server:8761/eureka
    fetchRegistry: true
    registerWithEureka: true